class Shipping

  def self.code_to_country(code)
    for country in self.all_countries
      return country.first if country.include?(code)
    end
    return code
  end

  def self.regions
    ["United Kingdom", "Europe", "Rest of the World"]
  end

  def self.great_britain
    [
    ["United Kingdom", "GB"]
    ]
  end
  
  def self.europe
    [
    ["Albania", "AL"],
    ["Andorra", "AD"],
    ["Austria", "AT"],
    ["Belgium", "BE"],
    ["Bosnia-Herzegovina", "BA"],
    ["Bulgaria", "BG"],
    ["Croatia", "HR"],
    ["Cyprus", "CY"],
    ["Czech Republic", "CZ"],
    ["Denmark", "DK"],
    ["Estonia", "EE"],
    ["Finland", "FI"],
    ["Faroe Islands", "FO"],
    ["France", "FR"],
    ["France (European Territory)", "FX"],
    ["Germany", "DE"],
    ["Gibraltar", "GI"],
    ["Greece", "GR"],
    ["Hungary", "HU"],
    ["Iceland", "IS"],
    ["Ireland", "IE"],
    ["Italy", "IT"],
    ["Latvia", "LV"],
    ["Liechtenstein", "LI"],
    ["Lithuania", "LT"],
    ["Luxembourg", "LU"],
    ["Malta", "MT"],
    ["Monaco", "MC"],
    ["Netherlands", "NL"],
    ["Norway", "NO"],
    ["Poland", "PL"],
    ["Portugal", "PT"],
    ["Romania", "RO"],
    ["Slovak Republic", "SK"],
    ["Slovenia", "SI"],
    ["Spain", "ES"],
    ["Sweden", "SE"],
    ["Switzerland", "CH"],
    ["Ukraine", "UA"],
    ["Vatican City State", "VA"]
    ]
  end
  
  def self.rest_of_the_world
    [
    ["United States", "US"],
    ["Canada", "CA"],
    ["Afghanistan", "AF"],
    ["Algeria", "DZ"],
    ["American Samoa", "AS"],
    ["Angola", "AO"],
    ["Anguilla", "AI"],
    ["Antarctica", "AQ"],
    ["Antigua and Barbuda", "AG"],
    ["Argentina", "AR"],
    ["Armenia", "AM"],
    ["Aruba", "AW"],
    ["Australia", "AU"],
    ["Azerbaidjan", "AZ"],
    ["Bahamas", "BS"],
    ["Bahrain", "BH"],
    ["Bangladesh", "BD"],
    ["Barbados", "BB"],
    ["Belize", "BZ"],
    ["Benin", "BJ"],
    ["Bhutan", "BT"],
    ["Bolivia", "BO"],
    ["Botswana", "BW"],
    ["Bouvet Island", "BV"],
    ["Brazil", "BR"],
    ["British Indian Ocean Territory", "IO"],
    ["Brunei Darussalam", "BN"],
    ["Burkina Faso", "BF"],
    ["Burundi", "BI"],
    ["Cambodia", "KH"],
    ["Cameroon", "CM"],
    ["Cape Verde", "CV"],
    ["Cayman Islands", "KY"],
    ["Central African Republic", "CF"],
    ["Chad", "TD"],
    ["Chile", "CL"],
    ["China", "CN"],
    ["Christmas Island", "CX"],
    ["Cocos (Keeling) Islands", "CC"],
    ["Colombia", "CO"],
    ["Comoros", "KM"],
    ["Cook Islands", "CK"],
    ["Costa Rica", "CR"],
    ["Djibouti", "DJ"],
    ["Dominica", "DM"],
    ["Dominican Republic", "DO"],
    ["East Timor", "TP"],
    ["Ecuador", "EC"],
    ["Egypt", "EG"],
    ["El Salvador", "SV"],
    ["Equatorial Guinea", "GQ"],
    ["Ethiopia", "ET"],
    ["Falkland Islands", "FK"],
    ["Fiji", "FJ"],
    ["Former USSR", "SU"],
    ["French Guyana", "GF"],
    ["French Southern Territories", "TF"],
    ["Gabon", "GA"],
    ["Gambia", "GM"],
    ["Georgia", "GE"],
    ["Ghana", "GH"],
    ["Greenland", "GL"],
    ["Grenada", "GD"],
    ["Guadeloupe (French)", "GP"],
    ["Guam (USA)", "GU"],
    ["Guatemala", "GT"],
    ["Guinea Bissau", "GW"],
    ["Guyana", "GY"],
    ["Haiti", "HT"],
    ["Heard and McDonald Islands", "HM"],
    ["Honduras", "HN"],
    ["Hong Kong", "HK"],
    ["India", "IN"],
    ["Indonesia", "ID"],
    ["Israel", "IL"],
    ["Jamaica", "JM"],
    ["Japan", "JP"],
    ["Jordan", "JO"],
    ["Kazakhstan", "KZ"],
    ["Kenya", "KE"],
    ["Kiribati", "KI"],
    ["Kuwait", "KW"],
    ["Kyrgyzstan", "KG"],
    ["Laos", "LA"],
    ["Lesotho", "LS"],
    ["Libya", "LY"],
    ["Macau", "MO"],
    ["Macedonia", "MK"],
    ["Madagascar", "MG"],
    ["Malawi", "MW"],
    ["Malaysia", "MY"],
    ["Maldives", "MV"],
    ["Mali", "ML"],
    ["Marshall Islands", "MH"],
    ["Martinique (French)", "MQ"],
    ["Mauritania", "MR"],
    ["Mauritius", "MU"],
    ["Mayotte", "YT"],
    ["Mexico", "MX"],
    ["Micronesia", "FM"],
    ["Moldavia", "MD"],
    ["Mongolia", "MN"],
    ["Montserrat", "MS"],
    ["Morocco", "MA"],
    ["Mozambique", "MZ"],
    ["Namibia", "NA"],
    ["Nauru", "NR"],
    ["Nepal", "NP"],
    ["Netherlands Antilles", "AN"],
    ["New Caledonia (French)", "NC"],
    ["New Zealand", "NZ"],
    ["Nicaragua", "NI"],
    ["Niger", "NE"],
    ["Nigeria", "NG"],
    ["Niue", "NU"],
    ["Norfolk Island", "NF"],
    ["Northern Mariana Islands", "MP"],
    ["Oman", "OM"],
    ["Pakistan", "PK"],
    ["Palau", "PW"],
    ["Panama", "PA"],
    ["Papua New Guinea", "PG"],
    ["Paraguay", "PY"],
    ["Peru", "PE"],
    ["Philippines", "PH"],
    ["Pitcairn Island", "PN"],
    ["Polynesia (French)", "PF"],
    ["Puerto Rico", "PR"],
    ["Qatar", "QA"],
    ["Reunion (French)", "RE"],
    ["Russian Federation", "RU"],
    ["Rwanda", "RW"],
    ["S. Georgia & S. Sandwich Isls.", "GS"],
    ["Saint Helena", "SH"],
    ["Saint Kitts & Nevis Anguilla", "KN"],
    ["Saint Lucia", "LC"],
    ["Saint Pierre and Miquelon", "PM"],
    ["Saint Tome (Sao Tome) and Principe", "ST"],
    ["Saint Vincent & Grenadines", "VC"],
    ["Samoa", "WS"],
    ["San Marino", "SM"],
    ["Saudi Arabia", "SA"],
    ["Senegal", "SN"],
    ["Seychelles", "SC"],
    ["Sierra Leone", "SL"],
    ["Singapore", "SG"],
    ["Solomon Islands", "SB"],
    ["South Africa", "ZA"],
    ["South Korea", "KR"],
    ["Sri Lanka", "LK"],
    ["Suriname", "SR"],
    ["Svalbard and Jan Mayen Islands", "SJ"],
    ["Swaziland", "SZ"],
    ["Tadjikistan", "TJ"],
    ["Taiwan", "TW"],
    ["Tanzania", "TZ"],
    ["Thailand", "TH"],
    ["Togo", "TG"],
    ["Tokelau", "TK"],
    ["Tonga", "TO"],
    ["Trinidad and Tobago", "TT"],
    ["Tunisia", "TN"],
    ["Turkey", "TR"],
    ["Turkmenistan", "TM"],
    ["Turks and Caicos Islands", "TC"],
    ["Tuvalu", "TV"],
    ["Uganda", "UG"],
    ["United Arab Emirates", "AE"],
    ["Uruguay", "UY"],
    ["USA Minor Outlying Islands", "UM"],
    ["Uzbekistan", "UZ"],
    ["Venezuela", "VE"],
    ["Vietnam", "VN"],
    ["Virgin Islands (British)", "VG"],
    ["Virgin Islands (USA)", "VI"],
    ["Wallis and Futuna Islands", "WF"],
    ["Western Sahara", "EH"],
    ["Yemen", "YE"],
    ["Zaire", "ZR"],
    ["Zambia", "ZM"],
    ["Vanuatu", "VU"],
    ]
  end
  
  def self.grouped_countries
    [
    ["United Kingdom", self.great_britain],
    ["Europe", self.europe],
    ["Rest of the Word", self.rest_of_the_world]
    ]
  end
  
  def self.all_countries
    (self.great_britain + self.europe + self.rest_of_the_world)
  end
  
end
